# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now=True)),
                ('WaterLevel', models.FloatField()),
                ('Turbidity', models.FloatField(null=True)),
                ('WaterConsumption', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterTap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now=True)),
                ('Proximity', models.FloatField()),
                ('WaterFlow', models.FloatField(null=True)),
            ],
        ),
    ]
